export type Activity = {
  id: number,
  name: string, 
  image: string | '', 
  reps: number | undefined, 
  sets: number | undefined, 
  isBilateral: boolean | false, 
  equipment: string[] | [], 
  weight: number | undefined, 
  weightUnits: string | undefined, 
  tags: string[] | [], 
  duration: number | undefined, 
  durationUnits: string | undefined,
  notes: string | undefined,
  instructions: string | undefined,
};
